import type {NextPage} from 'next';
import Head from 'next/head';
import {signIn} from 'next-auth/react';
import {useRouter} from 'next/router';
import {useState} from 'react';

const Auth: NextPage = () => {
  const router = useRouter();

  const [disabled, setDisabled] = useState(false);

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setDisabled(true);
    const result = await signIn('credentials', {
      redirect: false,
      username: e.currentTarget.username.value,
      password: e.currentTarget.password.value,
    });
    if (result?.ok) {
      router.replace('/');
      setDisabled(false);
      return;
    }
    alert('Credential is not valid');
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="max-w-[454px] m-auto text-center pt-40 px-4">
        <p className="text-blue text-md font-medium">omoui.design</p>
        <h1 className="my-12 text-grey text-xl font-medium">Admin</h1>

        <form onSubmit={onSubmit} className="flex flex-col gap-4 w-full">
          <input
            type="text"
            placeholder="username"
            name="username"
            id="username"
            required
          />
          <input
            type="password"
            placeholder="password"
            name="password"
            id="password"
            required
          />

          <button
            className="bg-blue text-white font-medium rounded-lg h-14"
            disabled={disabled}
          >
            Log in
          </button>
        </form>
      </section>
    </>
  );
};

export default Auth;
